### ISSUE TITLE
Message "successfully saved"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ooskapenaar/awarenet#396]
```
As commonly known the learners click "save" (blogs) quite often. Thats why 
Strix implemented the feature that the button disappears after clicked once. 
But then it takes ages to save an entry (especially at schools where we use the 
(slow) internet-connection). Because the learners can't click on save again 
they think it didn't work or it saved already so they leave the page and as a 
result the blog is not saved.
Thats why I think a popup or text like "successfully saved" is usefull.
What do you think?!

```

Original issue reported on code.google.com by `MrLordS...@gmail.com` on 16 Jan 2015 at 9:27

**Comment by AMWertlen** [comment]
News from Strix:
"
Have made a fix for the issue with blog posts saving slowly.  Should make the save action fast and do the other work later in the background - notifications, updating the stats, maintaining the cache, twitter etc.  While I was in there I found another way to make the blog cache and notifications more efficient, so that should help a little with overall speed.

This fix is not on the production instances yet, I'll do that tomorrow afternoon when I have access to them at the hub.
"

Thank you very much, Strix!!

**Comment by awarenetdev** [comment]
This should no longer be a problem for awarenet.eu, will be closed for all awarenet instances this weekend after next set of updates are applied.

**Comment by LarissaVSA** [comment]
Cool :P
